services:
  db:
    image: postgres:17
    env_file: ".env"
    environment:
      PGPORT: ${PGPORT}
    ports: 
      - "${PGPORT}:${PGPORT}"
    volumes:
      - ./app/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - etec
  api:
    environment:
      env_file: ".env"
    build:
      context: ./app/api
    ports:
      - "${VITE_API_PORT}:${VITE_API_PORT}"
    depends_on:
      - db
    volumes:
      - ./report:/usr/src/app/report
    networks:
      - etec
  web:
    environment:
      env_file: ".env"
    build: 
      context: ./app/web
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - etec

networks:
  etec:
    driver: bridge