services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports: 
      - "3306:3306"
    volumes:
      - ./app/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
  api:
    image: node:20-alpine
    build: ./app/api
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: mydb
  web:
    image: node:20-alpine
    build: ./app/web
    ports:
      - "8080:8080"
    depends_on:
      - api
    environment:
      API_URL: http://api:3000