services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_TCP_PORT: ${MYSQL_PORT}
      env_file: ".env"
    ports: 
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./app/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - etec
  api:
    build:
      context: ./app/api
      args:
        MYSQL_HOST: ${MYSQL_HOST}
        MYSQL_PORT: ${MYSQL_PORT}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${API_PORT}:3000"
    depends_on:
      - db
    volumes:
      - ./report:/usr/src/app/report
    networks:
      - etec
  # web:
  #   build: ./app/web
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
  #   environment:
  #     env_file: ".env"
  #   networks:
  #     - etec

networks:
  etec:
    driver: bridge