services:
  db:
    image: mariadb:lts
    env_file: ".env"
    environment:
      MYSQL_TCP_PORT: ${MARIADB_PORT}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
    ports: 
      - "${MARIADB_PORT}:${MARIADB_PORT}"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    networks:
      - etec
  # api:
  #   environment:
  #     env_file: ".env"
  #   build:
  #     context: ./app/api
  #     args:
  #       MARIADB_HOST: ${MARIADB_HOST}
  #       MARIADB_PORT: ${MARIADB_PORT}
  #       MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
  #       MARIADB_USER: ${MARIADB_USER}
  #       MARIADB_PASSWORD: ${MARIADB_PASSWORD}
  #       MARIADB_DATABASE: ${MARIADB_DATABASE}
  #   ports:
  #     - "${API_PORT}:3000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./report:/usr/src/app/report
  #   networks:
  #     - etec
  # web:
  #   environment:
  #     env_file: ".env"
  #   build: 
  #     context: ./app/web
  #     args:
  #       VITE_API_URL: ${VITE_API_URL}
  #       VITE_API_PORT: ${API_PORT}
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
  #   networks:
  #     - etec

networks:
  etec:
    driver: bridge