services:
  db:
    image: mysql:5.7
    environment:
      env_file: ".env"
    ports: 
      - "${DB_PORT}:3306"
    volumes:
      - /var/lib/mysql:/var/lib/mysql
      - ./app/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - etec
  # api:
  #   build: ./app/api
  #   ports:
  #     - "${API_PORT}:3000"
  #   depends_on:
  #     - db
  #   environment:
  #     env_file: ".env"
  #   volumes:
  #     - ./report:/usr/src/app/report
  #   networks:
  #     - etec
  # web:
  #   build: ./app/web
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - api
  #   environment:
  #     env_file: ".env"
  #   networks:
  #     - etec

networks:
  etec:
    driver: bridge