FROM node:20-alpine AS builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine

ARG MARIADB_HOST
ENV MARIADB_HOST=${MARIADB_HOST}

ARG MARIADB_PORT
ENV MARIADB_PORT=${MARIADB_PORT}

ARG MARIADB_ROOT_PASSWORD
ENV MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}

ARG MARIADB_USER
ENV MARIADB_USER=${MARIADB_USER}

ARG MARIADB_PASSWORD
ENV MARIADB_PASSWORD=${MARIADB_PASSWORD}

ARG MARIADB_DATABASE
ENV MARIADB_DATABASE=${MARIADB_DATABASE}

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package*.json ./
EXPOSE 3000

CMD ["npm", "run", "start:prod"]
