FROM node:20-alpine AS builder

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

FROM node:20-alpine

ARG PGHOST
ENV PGHOST=${PGHOST}

ARG PGPORT
ENV PGPORT=${PGPORT}

ARG POSTGRES_ROOT_PASSWORD
ENV POSTGRES_ROOT_PASSWORD=${POSTGRES_ROOT_PASSWORD}

ARG PGUSER
ENV PGUSER=${PGUSER}

ARG PGPASSWORD
ENV PGPASSWORD=${PGPASSWORD}

ARG POSTGRES_DATABASE
ENV POSTGRES_DATABASE=${POSTGRES_DATABASE}

WORKDIR /usr/src/app
COPY --from=builder /usr/src/app/node_modules ./node_modules
COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/package*.json ./
EXPOSE 3000

CMD ["npm", "run", "start:prod"]
